# Configuration file for ArUco detector project

# STEP 1
run_classification_experiments:
  paths:
    DATA_DIR_FILE: "./data/File3/arucoChallenging"
    CUSTOM_DATA_DIR_FILE: "./data/FileCustom1/arucoAugmented"
    EXPERIMENT_DIR: "./results/classification/STP1_classification_tests"
  experiments:
    datasets: ["./data/File3/arucoChallenging"]
    models: ["AlexNet"] #["MinimalCNN", "AlexNet-clean", "AlexNet", "ResNet18", "GoogLeNet"]
    batch_sizes: [32, 64]
    transformations: ["none", "random_rotation", "rotation_blur_noise"]
    num_workers: 8
    train_split: 0.8
    val_split: 0.1
    shuffle: true
    num_epochs: 50
    lr: 3.0e-4
    early_stopping_threshold: 96.0

# STEP 2
train_classifier:
  paths:
    DATA_DIR_FILE: "./data/FileCustom1/arucoAugmented"
    EXPERIMENT_DIR: "./results/classification/STP2_classification_trained_on_custom_data"
  training:
    final_model: "GoogLeNet"
    batch_size: 32
    num_workers: 8
    shuffle: true
    train_split: 0.95
    val_split: 0.025
    num_epochs: 50
    lr: 3.0e-4
    early_stopping_threshold: 99.9
  evaluation:
    batch_size: 256
    num_workers: 4
    original_datasets:
      File2: "./data/File2/arucoBasic"
      File3: "./data/File3/arucoChallenging"

# STEP 3
run_detection_experiments:
  paths:
    DATA_DIR_FILE: "./data/File5"
    CUSTOM_DATA_DIR_FILE: "./data/FileCustom2"
    EXPERIMENT_DIR: "./results/detection/STP3_detection_tests"
  experiments:
    datasets: ["./data/File5"]
    models: ["RetinaNet-ResNet50", "FasterRCNN-ResNet50", "MobileNetV3-Large-FPN"]
    batch_sizes: [4]
    num_workers: 2
    train_split: 0.8
    val_split: 0.1
    shuffle: true
    num_epochs: 100
    lr: 1.0e-4
    early_stopping_threshold: 98.0

# STEP 4
train_detector:
  paths:
    DATA_DIR_FILE: "./data/FileCustom2" 
    EXPERIMENT_DIR: "./results/detection/STP4_detection_trained_on_custom_data"
  training:
    final_model: "RetinaNet-ResNet50"
    batch_size: 8
    num_workers: 8
    shuffle: true
    train_split: 0.8
    val_split: 0.1
    num_epochs: 50
    lr: 1.0e-4
    early_stopping_threshold: 99.6
  evaluation:
    batch_size: 8
    num_workers: 2
    test_datasets:
      File4: "./data/File4"
      File5: "./data/File5"

# PREPROCESSING 1/2
dataset_augmentation:
  paths:
    DATA_DIR_RAW: "./data/File1/arucoRaw"
    DATA_DIR_AUGMENTED: "./data/FileCustom1/arucoAugmented"
  augmentation:
    total_transforms: 1000
    padding: 20
    rotation_range: [0, 360]
    blur_range: [0, 14]
    noise_range: [0.0, 0.1]
    noise_step: 0.025
    scale_range: [0.5, 1.0]

# PREPROCESSING 2/2
combine_office_tags:
  paths:
    ARUCO_DIR: "./data/FileCustom1/arucoAugmented"
    OFFICE_DIR: "./data/File6/officePics"
    OUTPUT_DIR: "./data/FileCustom2/combinedAugmented"
  image_processing:
    crop_size: 1000
    final_size: [224, 224]
    tag_size: [34, 34]
